
services:
  mysql:
      image: mysql
      container_name: wbd_mysql
      ports:
          - "33061:3306"
      environment:
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: php_mysql
      volumes:
          - db_data:/var/lib/mysql

volumes:
  db_data: